language: go

go:
  - 1.8
  - 1.9

before_install:
  - go get github.com/mattn/goveralls

sudo: false

script:
  - go vet -v ./...
  #- go test -v ./... # goveralls also runs this, but I want to see verbose test output in travis.
  - $HOME/gopath/bin/goveralls -service=travis-ci