#############################
#   Default configuration   #
#############################

# toggle for inFilename extension check (.pdf) 
checkFileNameExt: true

reader15: true
decodeAllStreams: false


# validationMode: 
# ValidationStrict,
# ValidationRelaxed,
# ValidationNone
validationMode: ValidationRelaxed

# eol for writing:
# EolLF
# EolCR
# EolCRLF
eol: EolLF

writeObjectStream: true
writeXRefStream: true
encryptUsingAES: true

# encryptKeyLength: max 256 
encryptKeyLength: 256

# permissions for encrypted files: 
# -3901 = 0xF0C3 (PermissionsNone)
# -1849 = 0xF8C7 (PermissionsPrint)
#    -1 = 0xFFFF (PermissionsAll)
permissions: -3901

# displayUnit:
# points
# inches
# cm
# mm
unit: points

# timestamp format: yyyy-mm-dd hh:mm
# Switch month and year by using: 2006-02-01 15:04
# See more at https://pkg.go.dev/time@go1.17.1#pkg-constants
timestampFormat: 2006-01-02 15:04

# date format: yyyy-mm-dd
dateFormat: 2006-01-02

# buffer size >= 100 for locating PDF header
headerBufSize: 100

# optimize duplicate content streams across pages
optimizeDuplicateContentStreams: false

# merge creates bookmarks
createBookmarks: true
